### ISSUE TITLE
Promotion of negative integers

### ISSUE THREAD

**Issue by nilskohl** [ckormanyos/wide-integer#108]
Hi,

currently evaluating the implementation. Stumbled across this conversion issue:

```cpp

int main()
{
    using w_t = math::wide_integer::uintwide_t< 32, std::uint32_t, void, true >;
    using ww_t = math::wide_integer::uintwide_t< 64, std::uint32_t, void, true >;

    w_t neg( -2 );
    ww_t neg_wide( -2 );
    ww_t neg_wide_cast = ww_t( neg );

    std::cout << neg << std::endl;
    std::cout << neg_wide << std::endl;
    std::cout << neg_wide_cast << std::endl;
}

```

which gives 

```
-2
-2
4294967294
```

I guess that promotion simply adds zeros to the left, but this
does not work for negative integers. Let me know if I am missing
something.

Tested with 7b9347e

Cheers,
Nils

**Comment by ckormanyos** [comment]
> promotion simply adds zeros to the left, but this does not work for negative integers. 

Good find. It is a bug.

I can reproduce the buggy behavior and will correct it ASAP.

Thank you Nils.

**Comment by nilskohl** [comment]
Nice! Thanks for the quick response.

**Comment by ckormanyos** [comment]
OK. There is a fix for this in main branch now.

To be honest, there is not a huge amount of testing and/or field experience with mixed limb-size/digit-counts, so there might be a few more problems lurking around in such conversion areas.

Thanks again for reporting this bug and please feel free to report more if/when found.

**Comment by nilskohl** [comment]
That was quick, thanks for the fix! :)

I will definitely let you know in case I stumble across something else.
