### ISSUE TITLE
Negative shifts

### ISSUE THREAD

**Issue by ArchaeaSoftware** [ckormanyos/wide-integer#14]
The shift operators should recurse on the negative count, e.g.

```
-      if     (n <  0) { operator>>=(n); }
+      if     (n <  0) { operator>>=(-n); }
```

**Comment by ckormanyos** [comment]
Thank you.
Good catch.
The fix is in and the tests are cycling.

**Comment by ckormanyos** [comment]
Should be fixed by #15

**Comment by ckormanyos** [comment]
@ArchaeaSoftware This should be fixed in master now. If you could try it that would be good to get independent confirmation of the fix.

Thanks.

**Comment by ckormanyos** [comment]
Tests pass. I will close this issue.
If more action is needed, we can reopen or create a new issue.

**Comment by ArchaeaSoftware** [comment]
Thanks for your prompt response!
