### ISSUE TITLE
How to convert uint256 to uint128?

### ISSUE THREAD

**Issue by avral** [ckormanyos/wide-integer#150]
Im trying to convert uint256 to system type __uint128(uint128_t) (the int will fit in 128 bits)
<img width="436" alt="Screenshot 2021-12-18 at 15 43 24" src="https://user-images.githubusercontent.com/10092436/146641521-9c0ce6d9-eb78-427b-870f-8e96d804bd51.png">

but having error
<img width="1071" alt="Screenshot 2021-12-18 at 15 44 09" src="https://user-images.githubusercontent.com/10092436/146641539-ba6c37da-544a-4750-9d09-4eaaf18aebf4.png">

is it even possible? if yes how can i do this?

**Comment by ckormanyos** [comment]
>  trying to convert uint256 to system type __uint128(uint128_t) (the int will fit in 128 bits)

Thank you for your query. I will take a look.

Are you using GCC or another compiler?

**Comment by avral** [comment]
Thank you! Im on mac m1 compiling with clang version 9.0.1

**Comment by avral** [comment]
@ckormanyos Excuse me!

#define WIDE_INTEGER_HAS_LIMB_TYPE_UINT64

Solved my problem! Thank you for the library!

**Comment by ckormanyos** [comment]
> #define WIDE_INTEGER_HAS_LIMB_TYPE_UINT64
> Solved my problem!

Thank you @avral
