### ISSUE TITLE
Establish a cleaner process for clang-tidy in CI

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#162]

**Comment by ckormanyos** [comment]
Back to the process topic. I noticed when running `clang-tidy` on multiple files, the tool actually filtered out repeated messages and reported them once only. Running the whole charge of files, however, in a single core will be too long for a CI job.

I will probably either batch/bash or GNUmake/CMake something and handle redundant messages with either a parser of a lexer in some sensible way. Once done, Ill add this to a single CI job.

**Comment by ckormanyos** [comment]
See also #145

**Comment by johnmcfarlane** [comment]
Are you sure about this? Could this be because the tool gives up when there's too much noise / difficulty parsing?

More importantly, could it ever miss something. Remember that the typical use case - once you've eliminated all the initial diagnostics - is that one or two errors is emitted on new code which introduces a new problem. Are you sure the tool would fail in this case?

It's easy to make things more complicated for a small benefit. But unless you're really bringing value, the complexity is almost never worth the burden it brings. Complex code is so much harder to work with.

**Comment by ckormanyos** [comment]
> Are you sure about this? 

Hardly sure at all, John. My running of the tool was probably just about as unsophisticated as possible.

I just hammered in this line, adding one more file at a time as soon as the message bulk got small enough to handle the next file(s).

I could put that line in a CI batch immediately. But running sequentially produces nice, filtered, unique messages but takes quite a few minutes on a single core.

```sh
clang-tidy-12 \
test/test.cpp \
test/test_uintwide_t_boost_backend.cpp \
test/test_uintwide_t_edge_cases.cpp \
test/test_uintwide_t_examples.cpp \
test/test_uintwide_t_float_convert.cpp \
test/test_uintwide_t_int_convert.cpp \
test/test_uintwide_t_n_base.cpp \
test/test_uintwide_t_n_binary_ops_base.cpp \
test/test_uintwide_t_spot_values.cpp \
examples/example000a_builtin_convert.cpp \
examples/example000_numeric_limits.cpp \
examples/example001_mul_div.cpp \
examples/example001a_div_mod.cpp \
examples/example002_shl_shr.cpp \
examples/example003_sqrt.cpp \
examples/example003a_cbrt.cpp \
examples/example004_rootk_pow.cpp \
examples/example005_powm.cpp \
examples/example005a_pow_factors_of_p99.cpp \
examples/example006_gcd.cpp \
examples/example007_random_generator.cpp \
examples/example008_miller_rabin_prime.cpp \
examples/example008a_miller_rabin_prime.cpp \
examples/example009_timed_mul.cpp \
examples/example009a_timed_mul_4_by_4.cpp \
examples/example009b_timed_mul_8_by_8.cpp \
examples/example010_uint48_t.cpp \
examples/example011_uint24_t.cpp \
examples/example012_rsa_crypto.cpp \
--header-filter=uintwide_t \
-checks=*,-fuchsia-*,-llvmlibc-*,-llvm-header-guard,-readability-identifier-naming,-readability-avoid-const-params-in-decls,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-altera-struct-pack-align -- -I. -I/mnt/c/boost/boost_1_78_0 -DWIDE_INTEGER_HAS_MUL_8_BY_8_UNROLL \
> tidy.txt
```

**Comment by johnmcfarlane** [comment]
Yeah, it's not a trivial task - especially when drowning in messages. Firstly, make sure the config file is valid YAML using an [online checker](http://www.yamllint.com/). Then run the checks in parallel to single out an offending .cpp file - it doesn't matter which one. Divide and conqueror: start running the single file and addressing the issues until that one's clean.

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane I ended up making a little 3-file make system based on old-school GNUmake with pass/fail in CI based on old-school `*nix` commands. Aside from using legace GNUmake, i think you might actually like some of the ideas in that process, although I'm aware that you've already solved this particular problem for your repos in your own way...

**Comment by ckormanyos** [comment]
All this is cycling in CI in #160

**Comment by ckormanyos** [comment]
Note to self: apply similar process for #161.
