### ISSUE TITLE
clang-tidy(-ness) to be cnl-ready

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#175]
The purpose of this issue is to ensure that the clang-tidy-ness of [ckormanyos/wide-integer](https://github.com/ckormanyos/wide-integer) is be ready to be used --- if desired --- directly off the rack in [johnmcfarlane/cnl](https://github.com/johnmcfarlane/cnl)

**Comment by johnmcfarlane** [comment]
I can pill in a newer revision of wide-integer into CNL at a time of my choosing. As such, any breakages that might occur won't break CNL immediately.

And the two projects use different CT configs so changes to one shouldn't generally affect the other.

**Comment by ckormanyos** [comment]
> can pull in a newer revision of wide-integer into CNL at a time of my choosing

I understand that, John. I admit this is a big ask and you might not have time for it and that's OK if you skip it.

> use different CT configs so changes to one shouldn't generally affect the other

I have adopted your settings in `.clang_tidy` because I really appreciated the way you had done that. So I actually would like to synchronize (at least at the outset) if at least `uintwide-t.h` satisfies your CT checks.

Having said all that I was quite perplexed by one anomaly --- and by this one particular thing only...

Consider the CT checks running on non-suppressed `uintwide_t.h` that you recently showed me [here](https://github.com/johnmcfarlane/cnl/runs/4755580131?check_suite_focus=true). These picked up a lot of cast warnings from `google-readability-casting`. But none of the CI jobs in wide-integer pick up these warnings --- even though the CMake jobs use your images and your CMake and the same (I think) `.clang-tidy` content. So I would really like some help if possible finding out what the difference is and why I can not pick up any `google-readability-casting` messages?

**Comment by johnmcfarlane** [comment]
Hi. I'll try and make some time to take a look at it this weekend. I'm also preparing a talk for the next couple of months though!

**Comment by ckormanyos** [comment]
> try and make some time to take a look at it this weekend.

Thanks John, but only if you find time. I'm satisfied with the setup and the only mystery is thet CI in wide-integer seemingly can't find `google-readability-casting`. I replaced most casts with C++ `static_cast` anyway, but the discrepancy between our setups --- seemingly identical --- does, however, confuse me.

Also feel free to let this issue go entirely if time is short, as I#m happy _enough_ with the setup(s).

Thanks very much for helping me set them up.

> I'm also preparing a talk for the next couple of months though!

Great! Good luck.

**Comment by ckormanyos** [comment]
> ... satisfied with the setup and the only mystery that I detect is that CI in wide-integer seemingly can't find google-readability-casting

I got this...

Hi @johnmcfarlane I am handling this myself on my fork of cnl in my `wide_integer_incubator` branch, with significantly reduced CI compared with cnl, but containing the tidy job(s) as you have them in your environment.

**Comment by ckormanyos** [comment]
I'll close this issue with no further action needed.

Cc: @johnmcfarlane

**Comment by ckormanyos** [comment]
This issue had been closed by accident. Tests in fork are running...

**Comment by ckormanyos** [comment]
Hello @johnmcfarlane this final batch of CT fixes runs green in both wide-integer CI as well as cnl CI (on push).

I have placed these changed in `uintwide_t.h` in my fork's ckormanyos/cnl's [`wide_integer_tidy`](https://github.com/ckormanyos/cnl/tree/wide_integer_tidy) branch --- which runs green in cnl's CI [on my push](https://github.com/ckormanyos/cnl/actions/runs/1707062863).

I have refrained from actually creating a PR. I can PR this with a mouse-click or two if you like, or you can simply get that file any time if that suits you.

If you'd like me to PR the tidy branch in my fork, please do, however, give me a heads up...

**Comment by johnmcfarlane** [comment]
I updated uintwide_t.h in order to get a clear picture of the change you're proposing. Please rebase on _main_ so that the change is clean (and doesn't include your recent changes in wide-integer). If that's green, it may make sense to disable the `NOLINTBEGIN`/`END` however, if you introduce a check failure in the future, it poses a dilemma for CNL as it won't be able to update _uintwide_t.h_ without changes to _wide_integer_. Thoughts?

**Comment by ckormanyos** [comment]
> If that's green, it may make sense to disable the NOLINTBEGIN/END ...

OK. I will take a look.

> ... however, if you introduce a check failure in the future, it poses a dilemma for CNL as it won't be able to update uintwide_t.h without changes to wide_integer. Thoughts?

Actually John, my favorite idea goes like this...

In my own CI, I clone cnl-main and run exactly your existing CI `clang-tidy` jobs --- whereby I'll integrate your YAML/image(s) into my own CI. It's just a couple of jobs more. So basically your tidy jobs would be taken as requirements for `wide-integer`'s branch protection rules. That way cnl-tidyness will be checked within cnl's near-to-own testing environment.

**Comment by johnmcfarlane** [comment]
Yeah, that would work. Though beware of complexity anywhere in software.

Alternatively, there *might* be provision for running one pipeline from another. I've not explored Actions thoroughly so who knows...

**Comment by ckormanyos** [comment]
> Yeah, that would work. Though beware of complexity anywhere in software.

I will give it a whirl.

> Alternatively, there might be provision for running one pipeline from another. I've not explored Actions thoroughly so who knows...

Actually, I really like your pipeline philosophy and your environment images. I also would like to possible adopt their use in some of my own projects, ... will take a while however.

**Comment by ckormanyos** [comment]
> rebase on main so that the change is clean (and doesn't include your recent changes in wide-integer)

Hi @johnmcfarlane I'm not fully sure if i did what you mean. I think I have accomplished this here.

Well, knowing me I did something not quite right with Git again. but I think the `NOLINT` markers can safely be removed with respect to my changes in `uintwide_t.h`.

I'm not planning much in wide-integer for a while (now that some of these recent large-scale improvements are done). But you can leave the `NOLINT` markers in if you feel that's safer until I set up some kind of double-check system with cnl/wide-integer on wide-integer's CI (as we briefly mention above).

I#ll give you a head's up when the CI of that kind is set up and running...

**Comment by johnmcfarlane** [comment]
Hi Chris. I integrated your changes in [CNL #1006](https://github.com/johnmcfarlane/cnl/pull/1006). Let's see how it goes. I haven't looked recently but I do have a large number of exclusions - many of which I aim to remove. Perhaps your project is already more Clang-Tidy-friendly!

**Comment by ckormanyos** [comment]
> Let's see how it goes.

OK.

> I haven't looked recently but I do have a large number of exclusions - many of which I aim to remove.

Hi John, great news.

Absolutely! Count me in on the fun. As you reduce your CT exclusions, I can easily follow suit. I really enjoy this kind of activity.

As far as i could tell, our test environments were --- aside from a strange parsing difference regarding one rule on C-style casts --- similar in how they check. So i can check in my own project, then check `uintwide_t.h` in my fork of cnl and iterate forward that way.

I'm definitely game to get in on the next round of tidying up!

**Comment by ckormanyos** [comment]
>> exclusions - many of which I aim to remove.

> Count me in on the fun.

Well I'm in the game. I took a preview on wide-integer with the rule set shown below and come up with less than 100 items in all test/example/header code together. Totally do-able.

```sh
TIDY_FLAGS   = --extra-arg-before=--driver-mode=g++       \
               --header-filter=uintwide_t                 \
               -warnings-as-errors=*                      \
               -checks=*,-fuchsia-*,-llvmlibc-*,-readability-avoid-const-params-in-decls
```

**Comment by ckormanyos** [comment]
I'll close this issue in lieu of future issues as we tighten up the tidyniess. In this issue, we've established the base starting point.

**Comment by johnmcfarlane** [comment]
Again, just want to warn you that clang tidy has a few odd usability
issues. If it ever stops complaining about you code, check it's still
working properly. Make sure it's parsing its config file correctly!

**Comment by ckormanyos** [comment]
> warn you that clang tidy has a few odd usability issues.

10-4. Copy that. I am becoming familiar with this sentiment, John!

>  Make sure it's parsing its config file correctly!

I'm actually having difficulty with that one. I still rely on command line params. I can use your ENV to check in cnl's domain. But I'm still figuring out why your tidy ENV differs from mine in 1 single rule only.

**Comment by ckormanyos** [comment]
See also #187 

Cc: @johnmcfarlane

**Comment by johnmcfarlane** [comment]
Oh, have you ruled out version differences?

**Comment by ckormanyos** [comment]
> have you ruled out version differences?

The sole difference between your ENV and mine is detection of `google-readability-casting`.

Indeed... You kind of channeled my thoughts, as I think it micht be a v12-versus-v13 difference, as the results are otherwise identical. In fact, I'll try a CI run with `clang-tidy-13`. But i don't know if i can `sudo apt get` it or I need to use (one of) your ENVs

I'll track it down one of these days...
