### ISSUE TITLE
Add a few embedded build(s) to CI

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#183]
As a first step, start with simply compiling for a few embedded targets available easily on Ubuntu such as `avr`, `arm-none-eabi`.

Compile with high warning levels and added warn flags and throw in a `-Werror` as well.

**Comment by johnmcfarlane** [comment]
Watching closely as I have [a reminder](https://github.com/johnmcfarlane/cnl/issues/811#issue-833867414) to test on small devices also. You may find the resources [here](https://gitlab.com/avr-libstdcxx) of interest.

**Comment by ckormanyos** [comment]
> Watching closely as I have a [reminder](https://github.com/johnmcfarlane/cnl/issues/811#issue-833867414) to test on small devices also.

Indeed. Thanks for recalling this, John. In my real-time-cpp project, I got far enough along (with added help from @gdobato) to build and load some rudimentary projects on QEMU for `arm-none-eabi` running ARM(R) Cortex(R)-CM4 core. As a final step, we still need to assess success based on the return value from main or set a run-time assessment in the simulated run.

This is work ongoing.

> You may find the resources [here](https://gitlab.com/avr-libstdcxx) of interest.

For building a wide-integer sample on the `avr`architecture, I will at first probably handle build-only. This is an interesting GCC port because it does _not_ ship with an STL implementation. I have a couple of STL options available that I use for these cases.

Thanks for the likns to these resources, I will take a look as well there...

**Comment by ckormanyos** [comment]
Worded out the following _long_ command line for future reference on bare-metal wide-integer builds.

This ling builds the example file

```sh
arm-none-eabi-g++ -x c++ -std=c++17 -Os -Wall -Wextra -pedantic -Wmain -Wundef -Wconversion -Wsign-conversion -Wunused-parameter -Wuninitialized -Wmissing-declarations -Wshadow -Wunreachable-code -Wswitch-default -Wswitch-enum -Wcast-align -Wmissing-include-dirs -Winit-self -Wfloat-equal -Wdouble-promotion -Wno-psabi -mcpu=cortex-m4 -mtune=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffast-math -mno-unaligned-access -mno-long-calls -finline-functions -finline-limit=32 -g -gdwarf-2 -fno-exceptions -ffunction-sections -fdata-sections -fno-rtti -fno-use-cxa-atexit -fno-exceptions -fno-threadsafe-statics -fno-enforce-eh-specs -ftemplate-depth=32 -Wzero-as-null-pointer-constant -I. -DWIDE_INTEGER_DISABLE_IOSTREAM -DWIDE_INTEGER_DISABLE_TRIVIAL_COPY_AND_STD_LAYOUT_CHECKS -DWIDE_INTEGER_NAMESPACE=ckormanyos -DWIDE_INTEGER_STANDALONE_EXAMPLE001_MUL_DIV examples/example001_mul_div.cpp -Wl,--gc-sections -Wl,-Map,./bin/example001_mul_div.map --specs=nano.specs --specs=nosys.specs -o bin/example001_mul_div.elf
```

**Comment by ckormanyos** [comment]
This particular `arm-none-eabi` compiler warns on `-pedantic` that nested namespaces are a C++17 feature. I was under the impression that nested namespaces are a C++11 feature. perhaps I am mistaken or I need to clear this up...

**Comment by ckormanyos** [comment]
> nested namespaces are a C++17 feature. I was under the impression that nested namespaces are a C++11 feature. perhaps I am mistaken or I need to clear this up...

I believe nested namespaces are a C++17 feature after some research. See #198 to track minor corrections regarding this.

**Comment by ckormanyos** [comment]
Just add some `arm-none-eabi` builds for now. Adding some `avr` builds would require me to clone my fork of [avr-libstdcpp](https://github.com/ckormanyos/avr-libstdcpp) or similar (which I will do, but in a leater step).
