### ISSUE TITLE
lcm_impl emits warning on GCC 11.2 x86_64

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#213]
This [line](https://github.com/ckormanyos/wide-integer/blob/ab472d264a734f0d5f19416fb94c2dad6414f105/math/wide_integer/uintwide_t.h#L5140) and the following similar [line](https://github.com/ckormanyos/wide-integer/blob/ab472d264a734f0d5f19416fb94c2dad6414f105/math/wide_integer/uintwide_t.h#L5144) should check if array bounds are `>= 2`. It seems like the compiler either is or might be correct. Anyway the bounds check is always a good idea.

**Comment by ckormanyos** [comment]
I ended up applying the bug label here because it actually could be an out-of-range access.

**Comment by johnmcfarlane** [comment]
What's the warning? There's some concern that GCC is emitting an increasing number of false-positives.
