### ISSUE TITLE
equivalent to mp::import_bits, mp::export_bits?

### ISSUE THREAD

**Issue by ckerr** [ckormanyos/wide-integer#297]
More a question than an issue, but I was wondering if there are any plans for an import/export bit utility similar to mp::import_bits() and mp::export_bits()?

From the 'Implementation goals' section of the README I'm not sure if it would be in-scope or not for the project, but I'd find it pretty useful :smile:

**Comment by ckormanyos** [comment]
Thanks for the suggestion @ckerr.

This seems like a reasonable idea. I have no direct planning for this, but let's leave this open as a potential new function.

I'll look around and see if we did anything similar in `Boost.Multiprecision`. There is also a pending idea for a namespace-local `to_string()` method, which has a direct (or close) parallel in std-C++. I'm not aware of a parallel for getting/setting bits in the C++ std for integral types, however. So a bit of work might be needed to specify input output parameter type(s).

I'm happy to keep this open and slowly work on an implementation...

**Comment by ckormanyos** [comment]
Hi Charles, it is finally time to start implementing these functions.

I'm liking [Boost.Multiprecision's interface](https://www.boost.org/doc/libs/1_80_0/libs/multiprecision/doc/html/boost_multiprecision/tut/import_export.html) for these. Would this be OK?

**Comment by ckerr** [comment]
@ckormanyos yep that would be perfect.

**Comment by ckormanyos** [comment]
A bit of progress has ben made.
A very preliminary (yet partially tested) version of `import_bits()` is now available in the main branch. More testing is needed.
The `export_bits()` function is in the works.

**Comment by ckormanyos** [comment]
Hello @ckerr the import/export functions are ready in a preliminary and tested state. They have cycled through CI in #315.

I will close this particular issue, but if anything arises when using these brand new functions, please file a bug if/as needed in a separate issue.
