### ISSUE TITLE
about import_bits/export_bits

### ISSUE THREAD

**Issue by chriscp-cat** [ckormanyos/wide-integer#316]
```c++
	uint8_t bin_128[] = {
		142, 215, 17, 233, 75, 7, 202, 91, 88, 53, 153, 106, 94, 112, 136, 40, 229, 3, 176, 116, 42, 179, 23,
		109, 103, 70, 57, 154, 157, 110, 148, 87, 86, 78, 175, 99, 6, 111, 16, 103, 142, 61, 253, 224, 39, 52,
		137, 252, 56, 116, 147, 71, 168, 16, 155, 245, 197, 97, 57, 69, 226, 13, 239, 164, 40, 228, 250, 130,
		128, 186, 150, 3, 64, 81, 241, 165, 43, 136, 99, 79, 124, 188, 50, 46, 152, 197, 205, 204, 103, 254, 61,
		143, 94, 31, 6, 98, 165, 16, 223, 175, 30, 87, 156, 176, 232, 56, 179, 56, 184, 220, 100, 141, 212, 201,
		55, 246, 199, 117, 28, 154, 51, 140, 5, 95, 102, 187, 133, 248
	};

	std::array<uint8_t, 128> out{};
	const int j = 50;
	using uint1024_t = math::wide_integer::uintwide_t<1024U, std::uint32_t>;
	uint1024_t big_int{ 0 };
	import_bits(big_int, bin_128, bin_128 + sizeof bin_128);
	uint1024_t big_int_ = big_int + j;
	for (int i = 0; i < j; ++i)
	{
		big_int++;
		export_bits(big_int, out.begin(), 8);
	}
	import_bits(big_int, out.begin(), out.end());

	std::cout << big_int << std::endl << big_int_ << std::endl;
	std::cout << (big_int_ == big_int);
```
export_bits don't seem to work properly

**Comment by chriscp-cat** [comment]
After I change `uintwide_t<1024U, std::uint32_t>` to `uintwide_t<1024U, std::uint8_t>`
It's working

**Comment by ckormanyos** [comment]
Hello @chriscp-cat I am investigating now.

At the moment, I am able to verify the correct import/export behavior for this data sample. These functions are, however, new. So a bit more testing might be in order.

I will cycle a few more tests and a dedicated pull request to verify the behavior.

Based on these results, I will try to analyze your example and see what's exactly going on.

**Comment by ckormanyos** [comment]
I think ther emight be an issue with the `chunk_size`. Let me investigate more tomorrow and also see how my own tests run through?

Thanks for your query. I'bb return with more details in a day or so.

Kind regards, Chris

**Comment by ckormanyos** [comment]
This is actually a bug regarding clearing the values of the output destination storage for export results. A fix will be available within a day or two. Many thanks for reporting this.

**Comment by chriscp-cat** [comment]
i have got it,Thanks for your work

**Comment by ckormanyos** [comment]
This is a bug in the wide-integer code. I will also be fixing that and adding relevant test cases soon.

**Comment by ckormanyos** [comment]
Thank ypou @chriscp-cat for finding this and pointing it out. It is (or was) an actual bug. This should now be fixed in the main branch.

If you find similar issues or anything else needed here, please feel free report any findings.

**Comment by chriscp-cat** [comment]
Thanks,I think the problem has been solved
