### ISSUE TITLE
Limb size & speedups

### ISSUE THREAD

**Issue by aptsurfer** [ckormanyos/wide-integer#36]
I appreciate the speed this library brings - it's very close to the speed of boost's multiprecision library for basic arithmetic.

I am trying to speed up uint256_t and uint512_t arithmetic in any possible way. I see that uint256_t and uint512_t are defined using 32-bit limbs. Is there anything prohibiting the use of 64-bit limbs instead?

I get a bunch of compile errors when I manually try to set the limb type to uint64_t. They seem to be template checks for the most part along with overflow warnings, but I don't know the code well enough to understand if we can work around them or not:
```
include/math/wide_integer/uintwide_t.h: In instantiation of ‘struct math::wide_integer::detail::uint_type_helper<128, void>’:
include/math/wide_integer/uintwide_t.h:637:125:   required from ‘class math::wide_integer::uintwide_t<256, long unsigned int>’
test_main.cpp:13:39:   required from here
include/math/wide_integer/uintwide_t.h:527:5: error: static assertion failed: Error: uint_type_helper is not intended to be used for this BitCount
     static_assert((   ((BitCount >= 8U) && (BitCount <= 64U))
     ^~~~~~~~~~~~~
include/math/wide_integer/uintwide_t.h: In instantiation of ‘class math::wide_integer::uintwide_t<256, long unsigned int>’:
test_main.cpp:13:39:   required from here
include/math/wide_integer/uintwide_t.h:645:5: error: static assertion failed: Error: Please check the characteristics of the template parameters ST and LT
     static_assert((    (std::numeric_limits<limb_type>::is_integer        == true)
     ^~~~~~~~~~~~~
include/math/wide_integer/uintwide_t.h: In instantiation of ‘class math::wide_integer::uintwide_t<512, long unsigned int, void>’:
test_main.cpp:15:56:   recursively required by substitution of ‘template<class UnknownUnsignedWideIntegralType, class> math::wide_integer::uintwide_t<256, long unsigned int>::operator math::wide_integer::uintwide_t<256, long unsigned int>::double_width_type<UnknownUnsignedWideIntegralType, <template-parameter-1-2> >() const [with UnknownUnsignedWideIntegralType = <missing>; <template-parameter-1-2> = <missing>]’
test_main.cpp:15:56:   required from here
include/math/wide_integer/uintwide_t.h:645:5: error: static assertion failed: Error: Please check the characteristics of the template parameters ST and LT
include/math/wide_integer/uintwide_t.h: In instantiation of ‘void math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::eval_divide_knuth(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&, math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>*) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’:
include/math/wide_integer/uintwide_t.h:984:26:   required from ‘math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>& math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::operator/=(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’
test_main.cpp:16:58:   required from here
include/math/wide_integer/uintwide_t.h:2029:80: warning: left shift count >= width of type [-Wshift-count-overflow]
  limb_type(double_limb_type(  double_limb_type(double_limb_type(1U) << std::numeric_limits<limb_type>::digits)
                                                ~~~~~~~~~~~~~~~~~~~~~^~~~~~
include/math/wide_integer/uintwide_t.h:2075:76: warning: left shift count >= width of type [-Wshift-count-overflow]
      const double_limb_type      u_j_j1 = (double_limb_type(uu[uj]) << std::numeric_limits<limb_type>::digits) + uu[uj - 1U];
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/math/wide_integer/uintwide_t.h:2089:61: warning: left shift count >= width of type [-Wshift-count-overflow]
                      <= double_limb_type(double_limb_type(t << std::numeric_limits<limb_type>::digits) + uu[uj - 2U])))
                                                           ~~^~~~~~
include/math/wide_integer/uintwide_t.h:2145:84: warning: left shift count >= width of type [-Wshift-count-overflow]
                     + double_limb_type(double_limb_type(previous_u) << std::numeric_limits<limb_type>::digits));
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
include/math/wide_integer/uintwide_t.h: In instantiation of ‘void math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::eval_divide_by_single_limb(math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::limb_type, uint_fast32_t, math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>*) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void; math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::limb_type = long unsigned int; uint_fast32_t = long unsigned int]’:
include/math/wide_integer/uintwide_t.h:2021:37:   required from ‘void math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::eval_divide_knuth(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&, math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>*) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’
include/math/wide_integer/uintwide_t.h:984:26:   required from ‘math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>& math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::operator/=(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’
test_main.cpp:16:58:   required from here
include/math/wide_integer/uintwide_t.h:1432:97: warning: left shift count >= width of type [-Wshift-count-overflow]
  - double_limb_type(double_limb_type(short_denominator) * hi_part)) << std::numeric_limits<limb_type>::digits);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/math/wide_integer/uintwide_t.h:1442:141: warning: left shift count >= width of type [-Wshift-count-overflow]
  - double_limb_type(double_limb_type(short_denominator) * hi_part)) << std::numeric_limits<limb_type>::digits);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/math/wide_integer/uintwide_t.h:1444:47: warning: right shift count >= width of type [-Wshift-count-overflow]
         *remainder = limb_type(long_numerator >> std::numeric_limits<limb_type>::digits);
                                ~~~~~~~~~~~~~~~^~~~~~
include/math/wide_integer/uintwide_t.h: In instantiation of ‘ST math::wide_integer::detail::make_hi(const LT&) [with ST = long unsigned int; LT = long unsigned int]’:
include/math/wide_integer/uintwide_t.h:2087:48:   required from ‘void math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::eval_divide_knuth(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&, math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>*) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’
include/math/wide_integer/uintwide_t.h:984:26:   required from ‘math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>& math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::operator/=(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’
test_main.cpp:16:58:   required from here
include/math/wide_integer/uintwide_t.h:591:5: error: static assertion failed: Error: Please check the characteristics of the template parameters ST and LT
     static_assert((    (std::numeric_limits<local_ushort_type>::is_integer == true)
     ^~~~~~~~~~~~~
include/math/wide_integer/uintwide_t.h:598:45: warning: right shift count >= width of type [-Wshift-count-overflow]
     return static_cast<local_ushort_type>(u >> std::numeric_limits<local_ushort_type>::digits);
                                           ~~^~~~~~
include/math/wide_integer/uintwide_t.h: In instantiation of ‘ST math::wide_integer::detail::make_lo(const LT&) [with ST = long unsigned int; LT = long unsigned int]’:
include/math/wide_integer/uintwide_t.h:1617:60:   required from ‘static void math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::eval_multiply_n_by_n_to_lo_part(math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::limb_type*, const limb_type*, const limb_type*, uint_fast32_t) [with long unsigned int RePhraseDigits2 = 256; const typename std::enable_if<((std::numeric_limits<LT>::digits * 4) == RePhraseDigits2)>::type* <anonymous> = 0; long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void; math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::limb_type = long unsigned int; uint_fast32_t = long unsigned int]’
include/math/wide_integer/uintwide_t.h:1495:38:   required from ‘static void math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::eval_mul_unary(math::wide_integer::uintwide_t<OtherDigits2, LimbType, AllocatorType>&, const math::wide_integer::uintwide_t<OtherDigits2, LimbType, AllocatorType>&, typename std::enable_if<((OtherDigits2 / std::numeric_limits<LT>::digits) < math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::number_of_limbs_karatsuba_threshold)>::type*) [with long unsigned int OtherDigits2 = 256; long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void; typename std::enable_if<((OtherDigits2 / std::numeric_limits<LT>::digits) < math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::number_of_limbs_karatsuba_threshold)>::type = void]’
include/math/wide_integer/uintwide_t.h:946:23:   required from ‘math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>& math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>::operator*=(const math::wide_integer::uintwide_t<Digits2, LimbType, AllocatorType>&) [with long unsigned int Digits2 = 256; LimbType = long unsigned int; AllocatorType = void]’
test_main.cpp:15:56:   required from here
include/math/wide_integer/uintwide_t.h:569:5: error: static assertion failed: Error: Please check the characteristics of the template parameters ST and LT
     static_assert((    (std::numeric_limits<local_ushort_type>::is_integer == true)
     ^~~~~~~~~~~~~

```

The reason I ask is that one of the goals of the library is to run on embedded systems, many of which I presume are 32-bit systems. I am running a 64-bit system and would like to know if speed gains are possible using full 64-bit limbs. It looks like Boost uses 32-bit limbs, too, so maybe there's a constraint I don't understand.

Other speedup tips would be very much appreciated, too.

**Comment by ckormanyos** [comment]
> I am trying to speed up uint256_t and uint512_t arithmetic in any possible way. I see that uint256_t and uint512_t are defined using 32-bit limbs. Is there anything prohibiting the use of 64-bit limbs instead?

Thank you for your interest and use of this LIB and for your excellent query.

At the moment, a big weak spot is that this LIB does not support the 64-bit `limb_type`. I will look into support of the 64-bit limb_type and report on progress.

> I am trying to speed up uint256_t and uint512_t arithmetic in any possible way.

If we get support for 64-bit limbs, then I would expect a speedup. Another option would be to explicitly support 256_by_256 multiplication, as this is already done in a specific template for the 4_by_4 multiplication case of 128-bit with 32-bit limb. For the speedup of the 4-by-4 128-bit multiplication case, see [this specialization of `eval_multiply_n_by_n_to_lo_part`](https://github.com/ckormanyos/wide-integer/blob/bcea233863fe0108d5296901ab53e9c46aa77267/math/wide_integer/uintwide_t.h#L1581)

All of this hinges on actually supporting the 64-bit limb type, as I will attempt to do. This one might take a bit of time, as it is running deep within ght depths of the LIB. I will take a look ASAP.

**Comment by ckormanyos** [comment]
See also #37

**Comment by ckormanyos** [comment]
That worked more easily than I thought.

From #37, we have:
There is support for 64-bit limb (on systems that support `unsigned __int128`).
To use 64-bit limb, compile with `WIDE_INTEGER_HAS_LIMB_TYPE_UINT64`.

@aptsurfer if you get a chance, could you give 64-bit limbs a try?

If that goes well, we can discuss explicit optimizations of 256 and 512 bit calculations.

**Comment by aptsurfer** [comment]
Absolutely amazing - I am already seeing a considerable speedup. Wow, this improvement alone will be such a big help to me! Thank you so much.

After profiling my code, it seems like 256-bit operations are where I'm doing most of my computation, and (as we'd expect) multiplication and division are where most of the CPU time is going. So I'm excited at the prospect of implementing explicit four-component multiplication. I appreciate the pointer to the existing 128-bit, 32-bit limb version - seems like a decent speedup there.

**Comment by ckormanyos** [comment]
See also #38 which now ensures that 4-by-4 multipliction specialization is successfully picked up for `uint256_t` with 64-bit limbs.

**Comment by ckormanyos** [comment]
4-by-4 multiplication is now included also for 64-bit limb. The case of optimizing 4-by-4 division is being tracked in #13

**Comment by aptsurfer** [comment]
Yes, I can definitely see a speedup in multiplication - fantastic!

I wish I could contribute to this project and give back somehow... if only I had more of a background in numerical methods.

**Comment by ckormanyos** [comment]
> Yes, I can definitely see a speedup in multiplication - fantastic!

Great. That makes me happy.

> could contribute to this project 

This issue and your positive feedback already did contribute.

There is also some low-hanging fruit. instances having 4 or 8 limbs are frequently used.
On these, operations add/sub/mul/div/shift-left/shift-right are very popular.
One simple improvement would be to unroll 4-limb operations add/sub/shift-left/shift-right for instances having exactly 4 limbs.
The same kind of `enable_if` technique used for the multiplication we have been using in this issue could be applied to these other operations. Add and subtract and shift are linear operations, so a huge improvement is not expected other than loop-unrolling. But if these are a bottleneck, then it helps.

**Comment by ckormanyos** [comment]
See #39.

I can make an example for addition to get the ball rolling.

**Comment by aptsurfer** [comment]
Cool - I am very busy for the next week or two, so I don't know how much I can do immediately, but this sounds simple enough for me to get started.

> I can make an example for addition to get the ball rolling.

That would be very helpful.

**Comment by ckormanyos** [comment]
Oh cool. There is no rush from my side. These are hobby projects are definitely on, let's say, definitely a slow roast from my side.

>> I can make an example for addition to get the ball rolling.

> That would be very helpful.

Example for addition is done with 12fd9a00a9fe0b42e94b32e18558df2e4d9f9dca

**Comment by aptsurfer** [comment]
After running a test application that does addition exclusively and comparing the results with or without addition unrolling, I didn't see any difference.

I then compared the generated assembly before and after the addition update, taking care to ensure that the binaries before and after were indeed from the different commits. It turns out that with -O3, g++ produces identical machine instructions! So I wonder whether manually unrolling the rest of these functions will actually be useful.

I should probably review multiplication again to make sure I actually did see a speedup.

**Comment by ckormanyos** [comment]
>  So I wonder whether manually unrolling the rest of these functions will actually be useful

Great observation. In general, operations add, sub, shl, shr are <img src="https://render.githubusercontent.com/render/math?math=O(N^1)"> algorithms, whereas classic multiplication and division are <img src="https://render.githubusercontent.com/render/math?math=O(N^2)"> (although there are sub-quadratic multiplication algorithms of particular interest).

We are finding the following:

- 1. A speedup expected for doubling the maximum limb size from 32-bit to to 64-bit is observed.
- 2. The unrolled multiplication algorithm for 4-by-4 multiply will likely bring speedup on most compiler/target systems.
- 3. Unrolled add, sub, shl, shr for 4 elements at high optimization brings little, as compilers unroll automatically (and also bring disadvantage of larger code size at lower optimization levels). Close #39.

It does not surprise me that level-3 optimization picks up a loop unroll with 4 elements. The unrolled loop can be beneficial if unrolling is desired even at other optimization levels, particularly at optimization speed. Close #39 and revert changes.

In light of all these considerations, a good compromise might be to
1. not unroll for linear operatioins,
2. do support unrolled 4-by-4 and 8-by-8 multiplication
3. tackle optimizations for division.
 
In this issue, we will handle 1 and 2. Point 3 is tracked in #2 and #13.

**Comment by ckormanyos** [comment]
Hi @aptsurfer Thanks for the good insights provided by yoursel in this issue.

As a final action on this particular issue, the compiler switch `WIDE_INTEGER_HAS_MUL_8_BY_8_UNROLL` can now optionally be used to unroll 8-by-8 multiplication loops(s). I did not find much benefit from this and leave this switch disabled by default. The 4-by-4 switch is, on the contrary, enabled by default and has no explicit compiler switch.

Having these options available, also combined with the 64-bit limb possibility on systems having `__int128`, I feel confident now CLOSING this issue.

Fee free please to re-open or open another issue, as questions or suggestions arise.
