### ISSUE TITLE
literal types

### ISSUE THREAD

**Issue by johnmcfarlane** [ckormanyos/wide-integer#41]
(This may be a dupe of #31 but types are not literals, i.e. not usable in constant expressions. It's also brought up in #10 but it's a separate concern from signedness so I thought it might be good to organise the threads into two.)

I took a quick look and things like `std::fill` and `std::array` may pose a problem in earlier language revisions, or even C++20. Would you be OK with abandoning C++11. Not necessary but very helpful because then you can keep variables and loops.

And would you consider abandoning C++14 and C++17? Even less necessary but still would reduce the amount of change necessary to achieve `constexpr`.

**Comment by ckormanyos** [comment]
Long answer to a short question. I would like to leave `uintwide_t` alone for the moment, other than a few potential tweaks and providing a safe area to benchmark performance stretching up with higher-order multiplication Toom-Cook and FFT.

We have (or are in the process of) hammering out the details of `intwide_t`, for which I actually recommend another new project. A lot of this is descrive in #10. Key reasons are C++20, clean new type more adherent to LEWG drafts, etc.

If (or when) `intwide_t` materializes, consider to (within that newer work) also support the unsigned type with similar top-level attributes.

This sketches out a rather long-term plan. If there are, however, some simplifications that we could make to the present `uintwide_t`, however, I can consider these. For the moment, I do actually like the support of C++11 or higher, although C++14, with is somewhat relaxed constraints on the depth of the bodies of `constexpr` functions makes it a lot easier to strive for compile-time constant. This can be negotiated.

**Comment by johnmcfarlane** [comment]
Just to see if it was possible, I gave wide-integer C++20 constexpr support in #42. This was mostly the tedious task of adding the `constexpr` keyword to many functions and requiring C++20 in the build configuration. Things that (unsurprisingly) didn't get constexprified:

* IO (the streaming operators)
* RNGs
* fixed_dynamic_array

I had to make a few little tweaks like value-initialising variables and replacing `memset` with `fill`. It didn't take much. (It's a pleasant codebase to work in.)

If you're concerned about `constexpr` interfering with benchmarks, you might want to play around with the branch. I'm confident that so long as you dynamically randomise your input properly, you should be seeing run-time results, not compiler-baked results. But you should probably check that none of the algorithms didn't mysteriously drop to 0s!

Would you be interested in further pursuing this branch, i.e. chasing C++17 and C++14 support? It gets more challenging -- mostly because fewer of the standard library algorithms are supported. So, for example, we might need to provide our own `fill` and `all_of`. If we can get to C++14, there's little reason not to move over. Being able to use these types as literals is an incredibly useful feature to provide -- aside from use in CNL.

**Comment by ckormanyos** [comment]
> Just to see if it was possible, I gave wide-integer C++20 constexpr support in #42.

Many thanks @johnmcfarlane for this ground-breaking stride forward. That is awesome! I left a few initial thoughts in the PR.

**Comment by ckormanyos** [comment]
> Would you be interested in further pursuing this branch, i.e. chasing C++17 and C++14 support? It gets more challenging -- mostly because fewer of the standard library algorithms are supported.

Yes. Either here directly, or, better yet in something like a version 2 reload of `uintwide_t`, `intwide_t`, etc. with proper storage, C++20 support and also (among other standardization migrations) improved `constexpr` correctness.

I'm thinking _new project_ instead of branch.

**Comment by johnmcfarlane** [comment]
Given I can see a route to C++20 constexpr support using the macros, I don't think the C++17,14,11 is so important now. CNL 2.x targets C++20 only currently, and it looks like it starts to quickly get difficult to support C++17 constexpr.

**Comment by ckormanyos** [comment]
> Given I can see a route to C++20 constexpr support using the macros, I don't think the C++17,14,11 is so important now.

Indeed, I've toned the revolution ideas down for the moment. In particular, it was cool how things actually worked out (or are in the process of working out) quite well with the C++20 `constexpr` support, as the method you've (we*ve) found does still retains compatibility with 11, 14, 17.

> CNL 2.x targets C++20 only currently, and it looks like it starts to quickly get difficult to support C++17 constexpr.

The final question I have is if we should stick with this repo, make a version 2, or migrate a derived work into the org you mention [in another post](https://github.com/johnmcfarlane/cnl/issues/796)

**Comment by johnmcfarlane** [comment]
@ckormanyos I think any of those works. I'm 75% convinced I should create a cnl-org, which I think would make a good home for a library like this.

One option I neglected to mention was straight-out replacing `cnl::dupliex_integer` with a `cnl::multiword_integer` which derives from `fixed_static_array`(*). I assumed you'd prefer to continue `wide-integer` along its own track but combining our efforts would be a big win for CNL. I already aim to support all the functionality of a wide integer type as well as using it to create an exceedingly powerful fixed-point type which users seem to be very keen to see.

(*) I've not mentioned `fixed_dynamic_array` so far -- mostly because it is impossible to `constexpr`ify in C++20 -- and I'm still unfamiliar with the architecture of these types. But I have some thoughts about it also:
* I think you could consolidate `fixed_static_array` and `fixed_dynamic_array` into a single adapter (a little like `std::stack`) in which storage is parameterised. Then that parameter would determine whether storage was dynamic or static:
  ```c++
  template<long NumWords, std::integral TopWord, multiword_storage Storage = static_array>
  class multiword_integer;
  ```
  (That last parameter might need to be a template template parameter.)
  I'm guessing the algorithms for both types are the same; they just operate on words in different areas of memory.
* Regardless of missing `constexpr` support, I think a dynamic memory type needs better support in CNL, i.e. I need to use forwarding everywhere so that these things are not copied more than is necessary. So I'm interested in using `fixed_dynamic_array` as a measure of interface and implementation quality.
* A further separation of concerns (I mentioned previously) is to separate the type from the operators. CNL does this with `custom_operator`, tags and `_impl::wrapper`. Basically, you only have to provide functors which contain the algorithms for each operator. You then create a tag which describes the type, e.g. `multiword_tag<12, int64_t>` for a 768-bit type and the type is created for you with: `using int768_t = cnl::_impl::wrapper<static_array<int64_t>, multiword_tag<12, int64_t>>;`.
  
  The benefit of this approach is that you don't need to write a full set of operators, or all of the boilerplate related to construction, conversion etc..

Sorry for the overwhelming brain dump there, but regardless of where this project goes, I'd be keen to contribute to its design where you think it would help.

Anyway, closing this now because literal types are in. Thanks!

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane without going into detail on all your points, i generally agree with all those thoughts.

I would like to retain the identity of the [wide-integer](https://github.com/ckormanyos/wide-integer) Repo and will be trying to move forward on:
- the signed integer type,
- a clean and terse epxression of Toom-Cook 3,4,
- improved sub-quadratic division,
- low-limb count high-speed division.

So these goals are not entirely consistent with another set of goals which is to generally move big integers, floats and fixed-points into a standardized form. My work here, in Boost and together with you is all hopefully generally moving in that direction.

Along these lines, I think we should, at some point in time (maybe after signed integer), pull out some of the stuff in this Repo, get it where you need it to be for CNL and contribute there.

Along the way, I would greatly appreciate and enjoy your help, advice and expert contributions in this little wide-integer project here. I really learned a lot from you in these contributions that you led us on.

Thanks @johnmcfarlane and let's keep gling on numbers.

I will officially close this issue.
