### ISSUE TITLE
Add construct from/cast to built in float types

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#47]
From standardization perspective, we will definitely need construction from and cast to built-in floating-point types `float`, `double` and `long double`.

Implement these. Along the way it might be necessary to resolve more clearly some of the existing (but not quite complete set) of casts to built in integral types.

**Comment by johnmcfarlane** [comment]
FYI, this is the current compiler error I'm hitting.

I'm working through an enormous amount of test code one error at a time. I can try and make the process less serial if you like but it seems like you are being kept pretty busy already!

One thing I cannot say with the current approach is how long the list of potential issues is. For instance, I support and tests for pretty-much every arithmetic operator. The list can be found [here](https://github.com/johnmcfarlane/cnl/blob/main/include/cnl/_impl/custom_operator/op.h). I also create a `4*uint8_t` 32-bit multi-word number and test it in place of fundamental integers. That means the type has to be very similar indeed in behavior to fundamentals.

That's just to warn you. I hope even if it gets too much, that feedback from experiments here will improve `uintwide_t`. However, I think this is doable with some time and patience.

**Comment by ckormanyos** [comment]
Well, I do have the internal mathematics for floating-point types rather well worked out. A few decisions are needed such as rounding, if any, when converting to/from floats.

> I'm working through an enormous amount of test code one error at a time. I can try and make the process less serial if you like but it seems like you are being kept pretty busy already!

Well you could dish out a couple at a time, or indicate regions of more/less concern/priority. Do yoou need more operators, interoperations, casts, constructions, or unlimited bit counts. I hope the list does not get very much longer than that, in terms of scope of the library.

>  create a 4*uint8_t 32-bit multi-word number and test it in place of fundamental integers.

Do you have any specific tests you need or known missing conversions/operators? This would be like `uintwide_t<32U, std::uint8_t, void, true>`.

**Comment by ckormanyos** [comment]
I guess I will move on to this issue next. I am kind of wondering how to convert simple stuff like `1.1E4F` or a bit harder `-1.1E50F` to `int256_t` and things, but I have most of the ideas.

My [soft_double project](https://github.com/ckormanyos/soft_double) that I cranked out between 2012 and now-ish... teaches me how to interconvert IEEE754.

**Comment by johnmcfarlane** [comment]
> Well you could dish out a couple at a time, or indicate regions of more/less concern/priority. Do you need more operators, interoperations, casts, constructions, or unlimited bit counts.

I'll try to drop as much as I can into Issues here. 

> I hope the list does not get very much longer than that, in terms of scope of the library.

The aim is simple: make types which act much like `signed` and `unsigned`, but using multiple limbs. Making something which behaves like native integers should be entirely within the scope of the library and should make it easier for users who want to replace native types and/or use the types interchangeably in generic code. 

However, the devil (and the list) is in the detail! `int` is a lot less simple than it looks. And aside from scouring through cppreference jotting down every list thing, I think the easiest thing to do -- as a first approximation -- is to test it in generic code where native and wide integers are both used. Hence I hope that regardless of the outcome for CNL, that the quality of wide-integer is improved.

> I guess I will move on to this issue next. I am kind of wondering how to convert simple stuff like 1.1E4F or a bit harder -1.1E50F to int256_t and things, but I have most of the ideas.

The challenge is doing it in a way that doesn't make assumptions about the bit layout of floating-point numbers. Maybe look at [`std::logb`](https://en.cppreference.com/w/cpp/numeric/math/logb) and [`frexp`](https://en.cppreference.com/w/cpp/numeric/math/frexp). Once you have the number broken down into a signed mantissa and an exponent, that's problem #1 solved. Then maybe tackly problem #2 afterwards: laying down those bits somewhere in the range of bits stored in your wide integer.

**Comment by ckormanyos** [comment]
> The challenge is doing it in a way that doesn't make assumptions about the bit layout of floating-point numbers.

Would you like to assume adherence to IEEE754-2008, at a minimum, I think radix 2 for convenient use of `frexp` and `ldexp`?

If adhere to IEEE754-2008, then I blieve the floating-point format is accessible via portable shifting.

**Comment by ckormanyos** [comment]
> Hence I hope that regardless of the outcome for CNL, that the quality of wide-integer is improved

Oh definitely, your help with C++20-style `constexpr` was elementally cool for this library, as was the turbo-motivation to get signed up and running. Cleaning up the code for `size_t` identified long-hidden errors and weaknesses.

The wide_integer library is greatly improved following your contributions and change requests. And we were careful not to break any existing code already using it. So I am really happy how that turned out so far.

As for what to do with the thing in CNL, if anything, ... you can use it directly, adapt some of its inner algorithms to your own needs or any combination thereof. I don't know if wide-integer will fulfill all the backend requirements for CNL but you can definitely use it either for the backend integer type itself (if we get that far), or simply as a collection of hints and tricks on how the arithmetic can be implemented.

**Comment by ckormanyos** [comment]
See also #75

**Comment by johnmcfarlane** [comment]
> Would you like to assume adherence to IEEE754-2008, at a minimum, I think radix 2 for convenient use of frexp and ldexp?
>
> If adhere to IEEE754-2008, then I blieve the floating-point format is accessible via portable shifting.

I don't know how well that will work in a constant expression... although `frexp` and `ldexp` aren't constexpr either.

**Comment by ckormanyos** [comment]
>> If adhere to IEEE754-2008

> don't know how well that will work in a constant expression

Yes. Those seem to be relevant considerations. If this assumption is made about the underlying format, it might be, believe it or not, actually the better way to strive for having a chance at `constexpr` construction. Using `frexp` will work, will also be portable, but might very likely break the `constexpt` context of constructors.

My prototyping at the moment uses `frexp` in the ctor from built-in floats, and it is not `constexpr` neither from design nor empirically from what the compiler(s) generate in terms of code.

**Comment by ckormanyos** [comment]
Prototype non-`constexpr` construction from built-in floating-point types is merged now.

Next step is cast to built-in floating-point types.

**Comment by ckormanyos** [comment]
Use the "Boost.Multiprecision way" for cast-to built-in floating-point types.

**Comment by ckormanyos** [comment]
Summary
- Use `frexp` and `ldexp` for construct/convert floats.
- This is not compile-time `constexpr`
- Use the "Boost-Way" for round-accumulate when casting from big integer to built-in float.

The way to `constexpr` correctness (if needed) whould ultimately involve writing own versions of floating-point manipulation requiring details on the floating-point format. This can only really be done if something like IEEE-754-2008 is assumed of with `enable_if` depending on some values of `numeric_limits`.

For the moment, this is in the leave as-is state unless motivation arises to seriously strive for `constexpr` correctness.
