### ISSUE TITLE
Reduce amount of Git cloning in CI

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#49]
Reduce amount of Git cloning in CI, which should be possible with the reduced dependencies of Math and (to a lesser extent) Multiprecision in develop branch.

**Comment by johnmcfarlane** [comment]
It's a pain going to the extra trouble (initially) but I'd highly recommend investing the time to create a docker image so that -- at least on Linux -- when the CI runner starts up, it already has a recent version of Boost installed. It would trim ~100s off every Linux job.

**Comment by ckormanyos** [comment]
> highly recommend investing the time to create a docker image

Tahnks for the sensible advice. I will try. That seems like a really good idea to save time/cycles/power in general.

In fact I have 3, soon to be 4, Repos needing Boost.Math and Boost.Multiprecision. In my embedded projects, I could theoretically make a docker image of a bunch of embedded compilers that are not even available via `apt get`.

**Comment by ckormanyos** [comment]
Provide further details to this issue.
- As a first step reduce the _amount_ of Biist.Math and Boost.Multiprecision needed (actually maybe only Multiprecision is needed).
- Subsequently figure out how to make a docker image of whatever is needed.

**Comment by ckormanyos** [comment]
Work has begun on this activity. There is progress. It appears as though, however, Random has a lot of dependencies. The overall amount of Boost could be reduced significantly if a specialized version of the needed random functions were to be implemented.

**Comment by ckormanyos** [comment]
Fixed by 58d7637b6d711252fd675efe51731423de855df7

**Comment by ckormanyos** [comment]
> Fixed

That means the first part is fixed. Re-open this issue for two further activities:

1. Reduce even more the amount of Boost cloning by writing project-specific replacements for what is used in Boost.Random
2. Optionally make a docker image of the remaining artifacts required to be cloned. This also makes sense in order to remove Boost potential breaking changes from changes in wide-integer.

**Comment by ckormanyos** [comment]
Update. Boost.Multiprecision is in the process of becoming standalone. When this is finished, both Math as well as Standalone will be essentially dependency-free. This will allow for further reductions in cloning submodules.

The second topic of making Docker images has, for the moment, stalled. Perhaps i'll pick that up again as soon as (or if) Boost.Multiprecision becomes standalone, potentially for Boost 1.79 if all goes well.

**Comment by ckormanyos** [comment]
> as soon as (or if) Boost.Multiprecision becomes standalone

Boost.Multiprecision in post-1.78 develop branch is predominantly standalone. Using it in CI essentially reduces the needed amount of cloning to very low levels.

For the moment, this is sufficient and is deemed fixed by 94ed69ce91eb53674732a0574bf5ef6c962d4add
