### ISSUE TITLE
digits now means width

### ISSUE THREAD

**Issue by johnmcfarlane** [ckormanyos/wide-integer#61]
When a type is unsigned, you can get away with using these terms interchangeably. Now, I'd caution against continuing to use the term 'digits' to mean number of binary digits in the storage. Not only is it inconsistent with CNL, but more importantly it doesn't match numeric limits.

The giveaway that this is problematic is the definition of `numeric_limits_uintwide_t_base::digits` where clearly this word is being used in to different ways within the project.

I'd recommend either

1. changing the first tparam from `Digits2` to `Width2` or `Bits`, or
2. using the value to mean something different when type is unsigned.

If you choose (1), I'd consider this issue to be low priority; you're just changing a name. But if you choose the second option, you'll be breaking the API of your signed type going forward so you might want to do this sooner.

**Comment by ckormanyos** [comment]
Note: Also include the Boost.Multiprecision backend to use `MyWidth2` instead of `MyDigits2`. This backend only handles the unsigned type(s) now. This issue does not include handling singed types in the Boost.Multiprecision backend.

**Comment by johnmcfarlane** [comment]
I'd forgotten to check Boost MP. It uses `Bits`.

**Comment by ckormanyos** [comment]
> forgotten to check Boost MP. It uses `Bits`.

Thank you. Actually, I'm kind of growing fond of `Width2` for the `wide_integer` itself library because the word _wide_ is so prevalent, even in the name `uintwide_t`. My _toy_ Boost.Multiprecision backend is another, longer story that'll probably need its own separate issue.
